game playable without errors, refactored client/client interface and add AlactrazMoveListener…
ShkembiAnis/Alcatraz pull request #20
Opened 2024-12-03 01:44 UTC by NilsPetsch1999

Spiel funktioniert mal, refactoring client und client interface +  AlcatrazMoveListener (eventuell noch Threading Probleme) +  paar todos reingeschrieben für Network Issues...., Game class gelöscht, weil unnötig
bitte anschauen und kurz mal ausprobieren... bei mir hats ganz gutgeklappt :D

2024-12-03 14:09 UTC, NilsPetsch1999 commented on client/src/main/java/alcatraz/client/Main.java
> +                                            lobbyPlayers.get(i).getClient().startGame(lobbyPlayers, 0);
i think this is not necesarry, since lobbyPlayer[0] will always be the owner of the lobby... looping through every sould work fine

2024-12-03 14:13 UTC, NilsPetsch1999 commented on client/src/main/java/alcatraz/client/Main.java
> -                                client.startGame(lobbyPlayers, 0);
Das war der ursprüngliche Fehler. 
Fixed: startGame muss mit dem Remote Object von jedem client aufgerufen werden, ansonsten ist die Alcatraz variable null

2024-12-04 16:06 UTC, albiosz requested changes
It looks good. Apart from the main function the code is really readable 👍

2024-12-04 16:06 UTC, albiosz commented on client/src/main/java/alcatraz/client/Main.java
> +                                        }else{
I think it would be more readable the owner of the lobby start the game first, and then we there is a loop of other players. The owner does not need to be in the loop, he is always first.

2024-12-04 16:06 UTC, albiosz commented on client/src/main/java/alcatraz/client/AlcatrazMoveListener.java
> +            SwingUtilities.invokeLater(() -> {
What for is the `SwingUtilities`? Does it execute the body in another thread?

2024-12-04 16:06 UTC, albiosz commented on client/src/main/java/alcatraz/client/Main.java
I would definitely refactor the huge try block by dividing it into smaller blocks. It does not need to be done in this PR, we could create an issue to do it later.

2024-12-05 12:03 UTC, albiosz commented on client/src/main/java/alcatraz/client/Main.java
> +                                        }else{
Now I see, that you mentioned it before ;)

2024-12-05 17:15 UTC, NilsPetsch1999 commented on client/src/main/java/alcatraz/client/Main.java
> +                                        }else{
since the owner is always first, just leave it as a simple loop ? because the owner always starts the game in the loop as the first player.

2024-12-05 19:28 UTC, merged